package dam2.di03_tareapascalseihon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paseihon
 */
public class MiRelojPascalSeihon extends javax.swing.JFrame {

    /**
     * Creates new form o
     */
    public MiRelojPascalSeihon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelImagen1 = new dam2.jpanelimagen.JpanelImagen();
        textcampo1 = new dam2.textocampo.textcampo();
        relojComponent1 = new dam2.relojpersonalizado.RelojComponent();
        relojComponent2 = new dam2.relojpersonalizado.RelojComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelImagen1.setBackground(new java.awt.Color(255, 255, 204));
        jpanelImagen1.setRutaImagen(new java.io.File("C:\\Users\\paseihon\\Desktop\\Carpeta_tarea\\DI03_TareaPascalSeihon\\src\\main\\java\\dam2\\di03_tareapascalseihon\\ImagenReloj.jfif"));

        textcampo1.setBackground(new java.awt.Color(204, 204, 255));
        textcampo1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        textcampo1.setForeground(new java.awt.Color(204, 0, 0));
        textcampo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textcampo1.setText("Mi Reloj");
        textcampo1.setTamanioTexto(20);
        textcampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcampo1ActionPerformed(evt);
            }
        });

        relojComponent1.setBackground(new java.awt.Color(204, 255, 51));
        relojComponent1.setForeground(new java.awt.Color(255, 255, 0));
        relojComponent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relojComponent1.setFormato24Horas(true);
        relojComponent1.setTamanioTexto(30);

        javax.swing.GroupLayout jpanelImagen1Layout = new javax.swing.GroupLayout(jpanelImagen1);
        jpanelImagen1.setLayout(jpanelImagen1Layout);
        jpanelImagen1Layout.setHorizontalGroup(
            jpanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelImagen1Layout.createSequentialGroup()
                .addGroup(jpanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelImagen1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(textcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(relojComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelImagen1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(relojComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jpanelImagen1Layout.setVerticalGroup(
            jpanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelImagen1Layout.createSequentialGroup()
                .addGroup(jpanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelImagen1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(textcampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelImagen1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(relojComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(relojComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelImagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelImagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textcampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcampo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiRelojPascalSeihon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiRelojPascalSeihon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiRelojPascalSeihon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiRelojPascalSeihon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiRelojPascalSeihon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    dam2.jpanelimagen.JpanelImagen jpanelImagen1;
    dam2.relojpersonalizado.RelojComponent relojComponent1;
    dam2.relojpersonalizado.RelojComponent relojComponent2;
    dam2.textocampo.textcampo textcampo1;
    // End of variables declaration//GEN-END:variables
}
